# Generated by Django 5.2.7 on 2025-10-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=14)),
                ('prevision', models.CharField(max_length=20)),
                ('accidenteLaboral', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
                ('Comobilidades', models.CharField(max_length=50)),
                ('funcionalidad', models.CharField(max_length=50)),
                ('motivoDerivacion', models.CharField(max_length=150)),
                ('prestacionRequerida', models.CharField(max_length=150)),
                ('evaluacion', models.CharField(max_length=150)),
                ('adicional', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
