# Generated by Django 5.2.8 on 2025-11-18 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='solicitudMedica',
            field=models.CharField(default='SIN_SOLICITUD', max_length=50),
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diagnostico', models.CharField(max_length=250)),
                ('medicacion', models.CharField(blank=True, max_length=250, null=True)),
                ('indicaciones', models.CharField(max_length=250)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.paciente')),
            ],
        ),
    ]
