# Generated by Django 5.2.8 on 2025-11-19 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_paciente_solicitudmedica_diagnostico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostico',
            old_name='Diagnostico',
            new_name='diagnostico',
        ),
    ]
