# Generated by Django 5.2.8 on 2025-11-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_rename_diagnostico_diagnostico_diagnostico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cama',
            name='ocupadas',
        ),
        migrations.RemoveField(
            model_name='cama',
            name='total',
        ),
        migrations.AddField(
            model_name='cama',
            name='Area',
            field=models.CharField(default='URGENCIAS', max_length=50),
        ),
        migrations.AddField(
            model_name='cama',
            name='disponibilidad',
            field=models.CharField(default='LIBRE', max_length=50),
        ),
    ]
