# Generated by Django 5.2.8 on 2025-11-25 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_remove_cama_ocupadas_remove_cama_total_cama_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cama',
            old_name='Area',
            new_name='area',
        ),
    ]
